# Generated by Django 6.1 on 2026-09-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_skill_delete_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.CharField(blank=True, null=True),
        ),
    ]
