# Generated by Django 5.2.17 on 2026-09-09 10:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_experience_delete_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('programming', 'Programming Language'), ('tools', 'Tools & Software'), ('language', 'Foreign Language')], default='programmming', max_length=20)),
                ('image', models.CharField(blank=True, null=True)),
            ],
        ),
    ]
