# Generated by Django 5.2.17 on 2026-09-10 07:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('pendidikan', 'Pendidikan')], default='pendidikan', max_length=20)),
                ('image', models.CharField(blank=True, null=True)),
                ('start', models.DateField()),
                ('end', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
